apiVersion: v1
kind: Service
metadata:
  name: product-web
  labels:
    app: product-web
spec:
  selector:
    app: product-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
