name: Build and Push Frontend to ECR

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ca-central-1 | \
          docker login --username AWS --password-stdin 011706314791.dkr.ecr.ca-central-1.amazonaws.com/meli-challenge/product-web

      - name: Build and Push Docker Image
        run: |
          docker build -t product-web .
          docker tag product-web:latest 011706314791.dkr.ecr.ca-central-1.amazonaws.com/meli-challenge/product-web:latest
          docker push 011706314791.dkr.ecr.ca-central-1.amazonaws.com/meli-challenge/product-web

      - name: Configure Kubernetes credentials (kubectl)
        run: |
          aws eks update-kubeconfig --region ca-central-1 --name mercadolibre-case

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
